package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AdisyonProducts generated by hbm2java
 */
public class AdisyonProducts  implements java.io.Serializable {


     private Integer adisyonProductsId;
     private Adisyon adisyon;
     private Products products;
     private Date purchaseDate;
     private Integer productQuantity;

    public AdisyonProducts() {
    }

    public AdisyonProducts(Adisyon adisyon, Products products, Date purchaseDate, Integer productQuantity) {
       this.adisyon = adisyon;
       this.products = products;
       this.purchaseDate = purchaseDate;
       this.productQuantity = productQuantity;
    }
   
    public Integer getAdisyonProductsId() {
        return this.adisyonProductsId;
    }
    
    public void setAdisyonProductsId(Integer adisyonProductsId) {
        this.adisyonProductsId = adisyonProductsId;
    }
    public Adisyon getAdisyon() {
        return this.adisyon;
    }
    
    public void setAdisyon(Adisyon adisyon) {
        this.adisyon = adisyon;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }
    public Integer getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }




}


