package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Adisyon generated by hbm2java
 */
public class Adisyon  implements java.io.Serializable {


     private Integer adisyonId;
     private Reservation reservation;
     private Set adisyonProductses = new HashSet(0);

    public Adisyon() {
    }

	
    public Adisyon(Reservation reservation) {
        this.reservation = reservation;
    }
    public Adisyon(Reservation reservation, Set adisyonProductses) {
       this.reservation = reservation;
       this.adisyonProductses = adisyonProductses;
    }
   
    public Integer getAdisyonId() {
        return this.adisyonId;
    }
    
    public void setAdisyonId(Integer adisyonId) {
        this.adisyonId = adisyonId;
    }
    public Reservation getReservation() {
        return this.reservation;
    }
    
    public void setReservation(Reservation reservation) {
        this.reservation = reservation;
    }
    public Set getAdisyonProductses() {
        return this.adisyonProductses;
    }
    
    public void setAdisyonProductses(Set adisyonProductses) {
        this.adisyonProductses = adisyonProductses;
    }




}


