package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private Integer departmentsId;
     private String departmentsName;
     private Set personnels = new HashSet(0);

    public Departments() {
    }

    public Departments(String departmentsName, Set personnels) {
       this.departmentsName = departmentsName;
       this.personnels = personnels;
    }
   
    public Integer getDepartmentsId() {
        return this.departmentsId;
    }
    
    public void setDepartmentsId(Integer departmentsId) {
        this.departmentsId = departmentsId;
    }
    public String getDepartmentsName() {
        return this.departmentsName;
    }
    
    public void setDepartmentsName(String departmentsName) {
        this.departmentsName = departmentsName;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }




}


