package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MailToken generated by hbm2java
 */
public class MailToken  implements java.io.Serializable {


     private Integer tokenId;
     private String token;
     private Date tokenDate;
     private String tokenMail;

    public MailToken() {
    }

    public MailToken(String token, Date tokenDate, String tokenMail) {
       this.token = token;
       this.tokenDate = tokenDate;
       this.tokenMail = tokenMail;
    }
   
    public Integer getTokenId() {
        return this.tokenId;
    }
    
    public void setTokenId(Integer tokenId) {
        this.tokenId = tokenId;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getTokenDate() {
        return this.tokenDate;
    }
    
    public void setTokenDate(Date tokenDate) {
        this.tokenDate = tokenDate;
    }
    public String getTokenMail() {
        return this.tokenMail;
    }
    
    public void setTokenMail(String tokenMail) {
        this.tokenMail = tokenMail;
    }




}


