package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personnel generated by hbm2java
 */
public class Personnel  implements java.io.Serializable {


     private Integer personnelId;
     private Departments departments;
     private String personnelName;
     private String personnelSurname;
     private Integer personnelAge;
     private String personnelTc;
     private boolean personnelAdmin;
     private String personnelMail;
     private String personnelPassword;
     private String personnelPhone;
     private String personnelImage;
     private Boolean personnelReservationAuthority;
     private Boolean personnelAdditionAuthority;
     private Boolean personnelManagmentAuhority;
     private Set eventPersonnelsForEventSenderId = new HashSet(0);
     private Set eventPersonnelsForPersonnelId = new HashSet(0);

    public Personnel() {
    }

	
    public Personnel(Departments departments, String personnelName, String personnelSurname, boolean personnelAdmin, String personnelMail) {
        this.departments = departments;
        this.personnelName = personnelName;
        this.personnelSurname = personnelSurname;
        this.personnelAdmin = personnelAdmin;
        this.personnelMail = personnelMail;
    }
    public Personnel(Departments departments, String personnelName, String personnelSurname, Integer personnelAge, String personnelTc, boolean personnelAdmin, String personnelMail, String personnelPassword, String personnelPhone, String personnelImage, Boolean personnelReservationAuthority, Boolean personnelAdditionAuthority, Boolean personnelManagmentAuhority, Set eventPersonnelsForEventSenderId, Set eventPersonnelsForPersonnelId) {
       this.departments = departments;
       this.personnelName = personnelName;
       this.personnelSurname = personnelSurname;
       this.personnelAge = personnelAge;
       this.personnelTc = personnelTc;
       this.personnelAdmin = personnelAdmin;
       this.personnelMail = personnelMail;
       this.personnelPassword = personnelPassword;
       this.personnelPhone = personnelPhone;
       this.personnelImage = personnelImage;
       this.personnelReservationAuthority = personnelReservationAuthority;
       this.personnelAdditionAuthority = personnelAdditionAuthority;
       this.personnelManagmentAuhority = personnelManagmentAuhority;
       this.eventPersonnelsForEventSenderId = eventPersonnelsForEventSenderId;
       this.eventPersonnelsForPersonnelId = eventPersonnelsForPersonnelId;
    }
   
    public Integer getPersonnelId() {
        return this.personnelId;
    }
    
    public void setPersonnelId(Integer personnelId) {
        this.personnelId = personnelId;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public String getPersonnelName() {
        return this.personnelName;
    }
    
    public void setPersonnelName(String personnelName) {
        this.personnelName = personnelName;
    }
    public String getPersonnelSurname() {
        return this.personnelSurname;
    }
    
    public void setPersonnelSurname(String personnelSurname) {
        this.personnelSurname = personnelSurname;
    }
    public Integer getPersonnelAge() {
        return this.personnelAge;
    }
    
    public void setPersonnelAge(Integer personnelAge) {
        this.personnelAge = personnelAge;
    }
    public String getPersonnelTc() {
        return this.personnelTc;
    }
    
    public void setPersonnelTc(String personnelTc) {
        this.personnelTc = personnelTc;
    }
    public boolean isPersonnelAdmin() {
        return this.personnelAdmin;
    }
    
    public void setPersonnelAdmin(boolean personnelAdmin) {
        this.personnelAdmin = personnelAdmin;
    }
    public String getPersonnelMail() {
        return this.personnelMail;
    }
    
    public void setPersonnelMail(String personnelMail) {
        this.personnelMail = personnelMail;
    }
    public String getPersonnelPassword() {
        return this.personnelPassword;
    }
    
    public void setPersonnelPassword(String personnelPassword) {
        this.personnelPassword = personnelPassword;
    }
    public String getPersonnelPhone() {
        return this.personnelPhone;
    }
    
    public void setPersonnelPhone(String personnelPhone) {
        this.personnelPhone = personnelPhone;
    }
    public String getPersonnelImage() {
        return this.personnelImage;
    }
    
    public void setPersonnelImage(String personnelImage) {
        this.personnelImage = personnelImage;
    }
    public Boolean getPersonnelReservationAuthority() {
        return this.personnelReservationAuthority;
    }
    
    public void setPersonnelReservationAuthority(Boolean personnelReservationAuthority) {
        this.personnelReservationAuthority = personnelReservationAuthority;
    }
    public Boolean getPersonnelAdditionAuthority() {
        return this.personnelAdditionAuthority;
    }
    
    public void setPersonnelAdditionAuthority(Boolean personnelAdditionAuthority) {
        this.personnelAdditionAuthority = personnelAdditionAuthority;
    }
    public Boolean getPersonnelManagmentAuhority() {
        return this.personnelManagmentAuhority;
    }
    
    public void setPersonnelManagmentAuhority(Boolean personnelManagmentAuhority) {
        this.personnelManagmentAuhority = personnelManagmentAuhority;
    }
    public Set getEventPersonnelsForEventSenderId() {
        return this.eventPersonnelsForEventSenderId;
    }
    
    public void setEventPersonnelsForEventSenderId(Set eventPersonnelsForEventSenderId) {
        this.eventPersonnelsForEventSenderId = eventPersonnelsForEventSenderId;
    }
    public Set getEventPersonnelsForPersonnelId() {
        return this.eventPersonnelsForPersonnelId;
    }
    
    public void setEventPersonnelsForPersonnelId(Set eventPersonnelsForPersonnelId) {
        this.eventPersonnelsForPersonnelId = eventPersonnelsForPersonnelId;
    }




}


