package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategories generated by hbm2java
 */
public class ProductCategories  implements java.io.Serializable {


     private Integer productCategoryId;
     private String productCategoryName;
     private Set productses = new HashSet(0);

    public ProductCategories() {
    }

	
    public ProductCategories(String productCategoryName) {
        this.productCategoryName = productCategoryName;
    }
    public ProductCategories(String productCategoryName, Set productses) {
       this.productCategoryName = productCategoryName;
       this.productses = productses;
    }
   
    public Integer getProductCategoryId() {
        return this.productCategoryId;
    }
    
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }
    public String getProductCategoryName() {
        return this.productCategoryName;
    }
    
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


