package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer productsId;
     private ProductCategories productCategories;
     private String productName;
     private double productPrice;
     private Set adisyonProductses = new HashSet(0);

    public Products() {
    }

	
    public Products(String productName, double productPrice) {
        this.productName = productName;
        this.productPrice = productPrice;
    }
    public Products(ProductCategories productCategories, String productName, double productPrice, Set adisyonProductses) {
       this.productCategories = productCategories;
       this.productName = productName;
       this.productPrice = productPrice;
       this.adisyonProductses = adisyonProductses;
    }
   
    public Integer getProductsId() {
        return this.productsId;
    }
    
    public void setProductsId(Integer productsId) {
        this.productsId = productsId;
    }
    public ProductCategories getProductCategories() {
        return this.productCategories;
    }
    
    public void setProductCategories(ProductCategories productCategories) {
        this.productCategories = productCategories;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public double getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }
    public Set getAdisyonProductses() {
        return this.adisyonProductses;
    }
    
    public void setAdisyonProductses(Set adisyonProductses) {
        this.adisyonProductses = adisyonProductses;
    }




}


