package com.hotelrezervation.model;
// Generated Dec 26, 2018 6:38:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer reservationId;
     private Rooms rooms;
     private Date reservationCreateDate;
     private Date reservationStartDate;
     private Date reservationEndDate;
     private String reservationName;
     private String reservationComment;
     private Boolean reservationHasBaby;
     private Integer reservationPeopleCount=1;
     private String reservationMail;
     private String reservationPhone;
     private double reservationPrice;
     private Boolean reservationHasPrice;
     private Set adisyons = new HashSet(0);

    public Reservation() {
    }

	
    public Reservation(Rooms rooms, Date reservationCreateDate, Date reservationStartDate, Date reservationEndDate) {
        this.rooms = rooms;
        this.reservationCreateDate = reservationCreateDate;
        this.reservationStartDate = reservationStartDate;
        this.reservationEndDate = reservationEndDate;
    }
    public Reservation(Rooms rooms, Date reservationCreateDate, Date reservationStartDate, Date reservationEndDate, String reservationName, String reservationComment, Boolean reservationHasBaby, Integer reservationPeopleCount, String reservationMail, String reservationPhone, double reservationPrice, Boolean reservationHasPrice, Set adisyons) {
       this.rooms = rooms;
       this.reservationCreateDate = reservationCreateDate;
       this.reservationStartDate = reservationStartDate;
       this.reservationEndDate = reservationEndDate;
       this.reservationName = reservationName;
       this.reservationComment = reservationComment;
       this.reservationHasBaby = reservationHasBaby;
       this.reservationPeopleCount = reservationPeopleCount;
       this.reservationMail = reservationMail;
       this.reservationPhone = reservationPhone;
       this.reservationPrice=reservationPrice;
       this.reservationHasPrice=reservationHasBaby;
       this.adisyons = adisyons;
    }
   
    public Integer getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }
    public Rooms getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }
    public Date getReservationCreateDate() {
        return this.reservationCreateDate;
    }
    
    public void setReservationCreateDate(Date reservationCreateDate) {
        this.reservationCreateDate = reservationCreateDate;
    }
    public Date getReservationStartDate() {
        return this.reservationStartDate;
    }
    
    public void setReservationStartDate(Date reservationStartDate) {
        this.reservationStartDate = reservationStartDate;
    }
    public Date getReservationEndDate() {
        return this.reservationEndDate;
    }
    
    public void setReservationEndDate(Date reservationEndDate) {
        this.reservationEndDate = reservationEndDate;
    }
    public String getReservationName() {
        return this.reservationName;
    }
    
    public void setReservationName(String reservationName) {
        this.reservationName = reservationName;
    }
    public String getReservationComment() {
        return this.reservationComment;
    }
    
    public void setReservationComment(String reservationComment) {
        this.reservationComment = reservationComment;
    }
    public Boolean getReservationHasBaby() {
        return this.reservationHasBaby;
    }
    
    public void setReservationHasBaby(Boolean reservationHasBaby) {
        this.reservationHasBaby = reservationHasBaby;
    }
    public Integer getReservationPeopleCount() {
        return this.reservationPeopleCount;
    }
    
    public void setReservationPeopleCount(Integer reservationPeopleCount) {
        this.reservationPeopleCount = reservationPeopleCount;
    }
    public String getReservationMail() {
        return this.reservationMail;
    }
    
    public void setReservationMail(String reservationMail) {
        this.reservationMail = reservationMail;
    }
    public String getReservationPhone() {
        return this.reservationPhone;
    }
    
    public void setReservationPhone(String reservationPhone) {
        this.reservationPhone = reservationPhone;
    }

    public double getReservationPrice() {
        return reservationPrice;
    }

    public void setReservationPrice(double reservationPrice) {
        this.reservationPrice = reservationPrice;
    }

    public Boolean getReservationHasPrice() {
        return reservationHasPrice;
    }

    public void setReservationHasPrice(Boolean reservationHasPrice) {
        this.reservationHasPrice = reservationHasPrice;
    }
    
    public Set getAdisyons() {
        return this.adisyons;
    }
    
    public void setAdisyons(Set adisyons) {
        this.adisyons = adisyons;
    }

    @Override
    public String toString() {
        return reservationName.toUpperCase();
    }




}


